### ISSUE TITLE
App crashing on touching the screen.

### ISSUE THREAD

**Issue by parth4054** [oabdelkarim/ARPaint#2]
Hi, according to the article we have to place our thumb in the detected plane square such that our thumb nail is visible. But as we touch our thumb nail by tapping on the screen, the app crashes.

**Comment by oabdelkarim** [comment]
Could you provide more info about the crash?

**Comment by parth4054** [comment]
sure, 

'NSInvalidArgumentException', reason: '-[ARFrame displayTransformWithViewportSize:orientation:]: unrecognized selector sent to instance 0x1c00f1e80'

**Comment by parth4054** [comment]
Let me know if the process I am following is correct.

1) start the app.
2) point towards a horizontal surface and wait for it to detect the plane.
3) after detecting the plane, put my thumb into the yellow frame such that my nail is clearly visible and tap on the screen where my thumb is located.

just after tapping, app crashes.
The demo video is just awesome!!

**Comment by jsm174** [comment]
In Beta 5 that method was deprecated. It looks like they changed the signature.

```
self.sceneView.session.currentFrame?.displayTransform(for: .portrait, viewportSize: self.sceneView.frame.size)
```

**Comment by oabdelkarim** [comment]
Yeah. It looks so. I will check the code again with Beta 5.

**Comment by douglastaquary** [comment]
I'm using `Xcode 9 -beta5`, and  it isn't work. Any tips?

**Comment by oabdelkarim** [comment]
Could you check it again please?

**Comment by douglastaquary** [comment]
Ok, i will be check again! :)

**Comment by douglastaquary** [comment]
O app is working! 🎉
