### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by liufsd** [oabdelkarim/ARPaint#3]
I have saw the rect and red point. but draw not working ?

**Comment by oabdelkarim** [comment]
Did you tap on Draw button?

**Comment by liufsd** [comment]
yes. and now i can touch my iphone screen then it will draw some point.
But your video show that ,you can draw by your finger on ARKit space. how can i do that ?
thank you.

**Comment by oabdelkarim** [comment]
You should make sure your thumbnail is shown on the screen then tap on your thumbnail as show in the screen to track it.

**Comment by liufsd** [comment]
ok, i will try it again.
