### ISSUE TITLE
Run Failed

### ISSUE THREAD

**Issue by gsrujana** [oabdelkarim/ARPaint#4]
Got few errors while trying to run:

1. Could not infer type for 'standardConfiguration' - Use of undeclared type 'ARWorldTrackingConfiguration'..

2. Replace 'for: UIInterfaceOrientation.portrait, viewportSize' with 'withViewportSize: UIInterfaceOrientation.portrait, orientation'

**Comment by gsrujana** [comment]
I am running on xcode beta version3

**Comment by oabdelkarim** [comment]
Please try the latest version of Xcode Beta and iOS 11

**Comment by gsrujana** [comment]
Thanks. That helped. However it detected finger only once. I do get the tracking state limited message. But how to run in a way that it detects finger each time. I ran it multiple times and most time it does not detect thumbnail
