### ISSUE TITLE
Crash on launch with xCode 9 beta 5

### ISSUE THREAD

**Issue by acsarraf** [oabdelkarim/ARPaint#6]
Crash report reads:

```
dyld: Symbol not found: _OBJC_CLASS_$_ARWorldTrackingConfiguration
  Referenced from: /var/containers/Bundle/Application/323B6BE2-C22F-44A6-A365-70D91F33058D/ARPaint.app/ARPaint
  Expected in: /System/Library/Frameworks/ARKit.framework/ARKit
 in /var/containers/Bundle/Application/323B6BE2-C22F-44A6-A365-70D91F33058D/ARPaint.app/ARPaint
```

Tried to add an exception breakpoint but it didn't take me to the problem.

**Comment by oabdelkarim** [comment]
What is your device specs?

**Comment by acsarraf** [comment]
iPhone 7 32 GB running iOS 11.0

It seems like Apple have made several changes with ARKit recently. I've even had trouble running their demo app recently, even though it was working fine.

**Comment by oabdelkarim** [comment]
And what beta version do you have on the device? I tested it on Xcode Beta 5 and iOS Beta 6 and it is working fine.

**Comment by acsarraf** [comment]
I will upgrade to iOS beta 6 tonight, I'm still running on beta 2, and let you know. It could be cause of that. Sorry for a late reply.

**Comment by acsarraf** [comment]
Yeah it's fine. Will close.
